export const users = [
  {
    id: 1,
    key: 1,
    name: 'Leanne Graham',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '01.02.2022',
    tags: ['React', 'JS'],
  },
  {
    id: 2,
    key: 2,
    name: 'Ervin Howell',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '02.02.2022',
    tags: ['Node'],
  },
  {
    id: 3,
    key: 3,
    name: 'Clementine Bauch',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '03.02.2022',
    tags: ['JS'],
  },
  {
    id: 4,
    key: 4,
    name: 'Patricia Lebsack',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '04.02.2022',
    tags: ['Node', 'JS'],
  },
  {
    id: 5,
    key: 5,
    name: 'Chelsey Dietrich',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '01.02.2022',
    tags: ['HTML/CSS'],
  },
  {
    id: 6,
    key: 6,
    name: 'Dennis Schulist',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '02.02.2022',
    tags: ['Node'],
  },
  {
    id: 7,
    key: 7,
    name: 'Kurtis Weissnat',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '03.02.2022',
    tags: ['Базы данных'],
  },
  {
    id: 8,
    key: 8,
    name: 'Nicholas Runolfsdottir V',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '04.02.2022',
    tags: ['JS', 'Базы данных'],
  },
  {
    id: 9,
    key: 9,
    name: 'Glenna Reichert',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '01.02.2022',
    tags: ['Базы данных'],
  },
  {
    id: 10,
    key: 10,
    name: 'Clementina DuBuque',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '02.02.2022',
    tags: ['HTML/CSS'],
  },
  {
    id: 11,
    key: 11,
    name: 'Leanne Graham',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '03.02.2022',
    tags: ['JS', 'Базы данных'],
  },
  {
    id: 12,
    key: 12,
    name: 'Ervin Howell"',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '04.02.2022',
    tags: ['React', 'JS'],
  },
  {
    id: 13,
    key: 13,
    name: 'Clementine Bauch',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '01.02.2022',
    tags: ['Node'],
  },
  {
    id: 14,
    key: 14,
    name: 'Patricia Lebsack',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '02.02.2022',
    tags: ['JS'],
  },
  {
    id: 15,
    key: 15,
    name: 'Chelsey Dietrich',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '03.02.2022',
    tags: ['Node', 'JS'],
  },
  {
    id: 16,
    key: 16,
    name: 'Dennis Schulist',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '04.02.2022',
    tags: ['HTML/CSS'],
  },
  {
    id: 17,
    key: 17,
    name: 'Kurtis Weissnat',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '01.02.2022',
    tags: ['Node'],
  },
  {
    id: 18,
    key: 18,
    name: 'Nicholas Runolfsdottir V',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '02.02.2022',
    tags: ['Базы данных'],
  },
  {
    id: 19,
    key: 19,
    name: 'Glenna Reichert',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '03.02.2022',
    tags: ['JS', 'Базы данных'],
  },
  {
    id: 20,
    key: 20,
    name: 'Clementina DuBuque',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '04.02.2022',
    tags: ['Базы данных'],
  },
  {
    id: 21,
    key: 21,
    name: 'Leanne Graham',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '01.02.2022',
    tags: ['HTML/CSS'],
  },
  {
    id: 22,
    key: 22,
    name: 'Leanne Graham',
    telegram: '@nickname',
    instagram: '@nickname',
    login: 'john.brown@gmail.com',
    startDate: '02.02.2022',
    tags: ['JS', 'Базы данных'],
  },
]
